### ISSUE TITLE
Safari doesn't set `type` on result of response.blob()

### ISSUE THREAD

**Issue by ansongoldade** [lynx-json/jsua#4]
When `transfer` is called when running in a Safari browser the blob object that is returned from response.blob() has a `type` value of "". The response.headers.get("content-type") has the correct value, but that is not being reflected on the blob object. Therefore anything that is dependent on that value is making incorrect decisions. 

Maybe use the media type portion of the `content-type` response header value to populate the type property on the content object that is resolved?

**Comment by danmork** [comment]
I'm pretty sure that I reported this issue to the WebKit team. I'll see if I can find any evidence of that and, if so, find the tracking number for the issue.

With respect to the idea of assigning the property on the `Blob` object instance. We can give that a try, but one issue with it is that I'm pretty sure that it resulted in a JS error in one of the Microsoft browsers.

Hooray for "standards".

**Comment by ansongoldade** [comment]
Of course ... everybody other than Chrome is getting some percentage right and the rest is left for us to plaster over the holes.

It may look funny in the http.js code, but we could append it to the `request` object instead of the blob object. Everything that consumes the result of that promise thinks of it as content so instead of checking `content.blob.type` they could just check `content.type`. That approach would get us around both the Safari and IE issues. Not solid on that, just a suggestion as we are thinking through it.

**Comment by danmork** [comment]
This appears to have been fixed in Safari 11.0. I am going to close this issue.
